# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            quru.com
tagline:          The open source IT solutions company
url:              http://quru.com
paginate:         1
baseurl:          /
author:
  name:           Quru
  url:            https://twitter.com/quru
  email:          info@quru.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/quruemail/quruemail
